language: node_js
cache:
  directories:
    - ~!@/.npm
node_js:
    - '9'
script: 'true'
git:
  depth: 3
scripts:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: build/
  target-branch: master 
  commit_message: 'deploy realese ${TRAVIS_TAG}'
  on: 
    branch: develop